force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>WR-{0000000}</displayFormat>
        <label>Warranty Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Warranty_Number__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Warranty Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/AdminEnrollmentDupeChecker_Test.cls
@IsTest(seealldata=false)
private without sharing class AdminEnrollmentDupeChecker_Test 
{
    static TestMethod void testTheBatch()
    {
        Enrollment__c enc1 = new Enrollment__c();
        enc1.Warranty_Number__c = '123456';
        enc1.Date_Ordered__c = SYSTEM.TODAY();
        insert enc1;

        Enrollment__c enc2 = new Enrollment__c();
        enc2.Warranty_Number__c = '123457';
        enc2.Date_Ordered__c = SYSTEM.TODAY().addDays(-10);
        insert enc2;

        AdminEnrollmentDupeChecker aedc = new AdminEnrollmentDupeChecker();
        Test.startTest();
        Database.executeBatch(aedc);
        Test.stopTest();
    }
}