force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>WR-{0000000}</displayFormat>
        <label>Warranty Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Agency_Office__c.field-meta.xml
<CustomField>
    <fullName>Agency_Office__c</fullName>
    <label>Agency / Office</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Agent_Address__c.field-meta.xml
<CustomField>
    <fullName>Agent_Address__c</fullName>
    <label>Agent Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Agent_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Agent_First_Name__c</fullName>
    <label>Agent First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Agent_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Agent_Last_Name__c</fullName>
    <label>Agent Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Agent_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Agent_Zip_Code__c</fullName>
    <label>Agent Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Buyer_Date_Ordered__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Date_Ordered__c</fullName>
    <label>Buyer Date Ordered</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/BUYER_FIRST_NAME__c.field-meta.xml
<CustomField>
    <fullName>BUYER_FIRST_NAME__c</fullName>
    <label>BUYER FIRST NAME</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/BUYER_LAST_NAME__c.field-meta.xml
<CustomField>
    <fullName>BUYER_LAST_NAME__c</fullName>
    <label>BUYER LAST NAME</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Buyer_Name_Populated__c.field-meta.xml
<CustomField>
    <fullName>Buyer_Name_Populated__c</fullName>
    <label>Buyer Name Populated</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/CCMID_of_Agency__c.field-meta.xml
<CustomField>
    <fullName>CCMID_of_Agency__c</fullName>
    <label>CCMID of Agency (on import)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/CCMID_of_Agent__c.field-meta.xml
<CustomField>
    <fullName>CCMID_of_Agent__c</fullName>
    <label>CCMID of Agent (on import)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/NAME_FIRST__c.field-meta.xml
<CustomField>
    <fullName>NAME_FIRST__c</fullName>
    <label>NAME_FIRST</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/NAME_LAST__c.field-meta.xml
<CustomField>
    <fullName>NAME_LAST__c</fullName>
    <label>NAME_LAST</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Seller_Date_Ordered__c.field-meta.xml
<CustomField>
    <fullName>Seller_Date_Ordered__c</fullName>
    <label>Seller Date Ordered</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/SELLER_FIRST_NAME__c.field-meta.xml
<CustomField>
    <fullName>SELLER_FIRST_NAME__c</fullName>
    <label>SELLER FIRST NAME</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/SELLER_LAST_NAME__c.field-meta.xml
<CustomField>
    <fullName>SELLER_LAST_NAME__c</fullName>
    <label>SELLER LAST NAME</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Seller_Name_Populated__c.field-meta.xml
<CustomField>
    <fullName>Seller_Name_Populated__c</fullName>
    <label>Seller Name Populated</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Used by EnrollmentRoundup batch job</description>
    <inlineHelpText>Used by EnrollmentRoundup batch job</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Picked up by Queueable</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Warranty_Number__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Number__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Warranty Number</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Warranty_Type__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Type__c</fullName>
    <label>Warranty Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BCW</fullName>
            </value>
            <value>
                <fullName>BDW</fullName>
            </value>
            <value>
                <fullName>NHW</fullName>
            </value>
            <value>
                <fullName>ODW</fullName>
            </value>
            <value>
                <fullName>SHW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EnrollmentHandler_Test.cls
@isTest
private with sharing class EnrollmentHandler_Test 
{
    static TestMethod void insertBCWRecord()
    {
        Enrollment__c Enr = new Enrollment__c();
        Enr.Status__c = 'New';
        Enr.Agency_Office__c = 'Test Office';
        Enr.Agent_Address__c = 'Test Street 1';
        Enr.CCMID_of_Agency__c = 'Agency1000';
        Enr.Agent_Zip_Code__c = '99999';
        Enr.Agent_First_Name__c = 'JOHN';
        Enr.Agent_Last_Name__c = 'DOE';
        Enr.CCMID_of_Agent__c = 'Agent8000';
        Enr.NAME_FIRST__c = 'Billy';
        Enr.NAME_LAST__c = 'Buyer';
        Enr.Warranty_Type__c = 'BCW';
        Enr.Warranty_Number__c = '123456';
        Enr.Date_Ordered__c = SYSTEM.TODAY();

        Test.startTest();
        insert Enr;
        Test.stopTest();

        Enrollment__c enrAfter = [SELECT Id, BUYER_FIRST_NAME__c, BUYER_LAST_NAME__c, NAME_FIRST__c, NAME_LAST__c,
                                    Buyer_Date_Ordered__c
                                FROM Enrollment__c 
                                WHERE Id = :Enr.Id LIMIT 1];
        SYSTEM.assertEquals(enrAfter.BUYER_FIRST_NAME__c, enrAfter.NAME_FIRST__c);
        SYSTEM.assertEquals(enrAfter.BUYER_LAST_NAME__c, enrAfter.NAME_LAST__c);
        SYSTEM.assertEquals(enrAfter.Buyer_Date_Ordered__c, SYSTEM.TODAY());
    }

    static TestMethod void insertSHWRecord()
    {
        Enrollment__c Enr = new Enrollment__c();
        Enr.Status__c = 'New';
        Enr.Agency_Office__c = 'Test Office';
        Enr.Agent_Address__c = 'Test Street 1';
        Enr.CCMID_of_Agency__c = 'Agency1000';
        Enr.Agent_Zip_Code__c = '99999';
        Enr.Agent_First_Name__c = 'JOHN';
        Enr.Agent_Last_Name__c = 'DOE';
        Enr.CCMID_of_Agent__c = 'Agent8000';
        Enr.NAME_FIRST__c = 'Sara';
        Enr.NAME_LAST__c = 'Seller';
        Enr.Warranty_Type__c = 'SHW';
        Enr.Warranty_Number__c = '123456';
        Enr.Date_Ordered__c = SYSTEM.TODAY();

        Test.startTest();
        insert Enr;
        Test.stopTest();

        Enrollment__c enrAfter = [SELECT Id, SELLER_FIRST_NAME__c, SELLER_LAST_NAME__c, NAME_FIRST__c, NAME_LAST__c,
                                    Seller_Date_Ordered__c
                                FROM Enrollment__c 
                                WHERE Id = :Enr.Id LIMIT 1];
        SYSTEM.assertEquals(enrAfter.SELLER_FIRST_NAME__c, enrAfter.NAME_FIRST__c);
        SYSTEM.assertEquals(enrAfter.SELLER_LAST_NAME__c, enrAfter.NAME_LAST__c);
        SYSTEM.assertEquals(enrAfter.Seller_Date_Ordered__c, SYSTEM.TODAY());
    }

    static TestMethod void updateToBCWRecord()
    {
        Enrollment__c Enr = new Enrollment__c();
        Enr.Status__c = 'New';
        Enr.Agency_Office__c = 'Test Office';
        Enr.Agent_Address__c = 'Test Street 1';
        Enr.CCMID_of_Agency__c = 'Agency1000';
        Enr.Agent_Zip_Code__c = '99999';
        Enr.Agent_First_Name__c = 'JOHN';
        Enr.Agent_Last_Name__c = 'DOE';
        Enr.CCMID_of_Agent__c = 'Agent8000';
        Enr.NAME_FIRST__c = 'Johnny';
        Enr.NAME_LAST__c = 'Nobody';
        Enr.Warranty_Number__c = '123456';
        
        insert Enr;

        
        Enrollment__c enrAfterInsert = [SELECT Id, Warranty_Type__c, BUYER_FIRST_NAME__c, BUYER_LAST_NAME__c, Buyer_Name_Populated__c,
                                            Buyer_Date_Ordered__c
                                        FROM Enrollment__c 
                                        WHERE Id = :Enr.Id LIMIT 1];

        SYSTEM.assertEquals(enrAfterInsert.BUYER_FIRST_NAME__c, null);
        SYSTEM.assertEquals(enrAfterInsert.BUYER_LAST_NAME__c, null);
        SYSTEM.assertEquals(enrAfterInsert.Buyer_Name_Populated__c, null);
        SYSTEM.assertEquals(enrAfterInsert.Buyer_Date_Ordered__c, null);

        Test.startTest();
            enrAfterInsert.Warranty_Type__c = 'BCW';
            enrAfterInsert.Date_Ordered__c = SYSTEM.TODAY();
            update enrAfterInsert;
        Test.stopTest();

        Enrollment__c enrAfterUpdate = [SELECT Id, BUYER_FIRST_NAME__c, BUYER_LAST_NAME__c, Buyer_Name_Populated__c, NAME_FIRST__c, NAME_LAST__c,
                                            Buyer_Date_Ordered__c FROM Enrollment__c 
                                        WHERE Id = :Enr.Id LIMIT 1];

        SYSTEM.assertEquals(enrAfterUpdate.BUYER_FIRST_NAME__c, enrAfterUpdate.NAME_FIRST__c);
        SYSTEM.assertEquals(enrAfterUpdate.BUYER_LAST_NAME__c, enrAfterUpdate.NAME_LAST__c);
        SYSTEM.assertNotEquals(enrAfterUpdate.Buyer_Name_Populated__c, null);
        SYSTEM.assertEquals(enrAfterUpdate.Buyer_Date_Ordered__c, SYSTEM.TODAY());
    }


    static TestMethod void updateToSHWRecord()
    {
        Enrollment__c Enr = new Enrollment__c();
        Enr.Status__c = 'New';
        Enr.Agency_Office__c = 'Test Office';
        Enr.Agent_Address__c = 'Test Street 1';
        Enr.CCMID_of_Agency__c = 'Agency1000';
        Enr.Agent_Zip_Code__c = '99999';
        Enr.Agent_First_Name__c = 'JOHN';
        Enr.Agent_Last_Name__c = 'DOE';
        Enr.CCMID_of_Agent__c = 'Agent8000';
        Enr.NAME_FIRST__c = 'Johnny';
        Enr.NAME_LAST__c = 'Nobody';
        Enr.Warranty_Number__c = '123456';
        
        insert Enr;

        
        Enrollment__c enrAfterInsert = [SELECT Id, Warranty_Type__c, SELLER_FIRST_NAME__c, SELLER_LAST_NAME__c, Seller_Name_Populated__c,
                                            Seller_Date_Ordered__c
                                        FROM Enrollment__c 
                                        WHERE Id = :Enr.Id LIMIT 1];

        SYSTEM.assertEquals(enrAfterInsert.SELLER_FIRST_NAME__c, null);
        SYSTEM.assertEquals(enrAfterInsert.SELLER_LAST_NAME__c, null);
        SYSTEM.assertEquals(enrAfterInsert.Seller_Name_Populated__c, null);
        SYSTEM.assertEquals(enrAfterInsert.Seller_Date_Ordered__c, null);

        Test.startTest();
            enrAfterInsert.Warranty_Type__c = 'SHW';
            enrAfterInsert.Date_Ordered__c = SYSTEM.TODAY();
            update enrAfterInsert;
        Test.stopTest();

        Enrollment__c enrAfterUpdate = [SELECT Id, SELLER_FIRST_NAME__c, SELLER_LAST_NAME__c, Seller_Name_Populated__c, NAME_FIRST__c, NAME_LAST__c,
                                            Seller_Date_Ordered__c 
                                        FROM Enrollment__c 
                                        WHERE Id = :Enr.Id LIMIT 1];

        SYSTEM.assertEquals(enrAfterUpdate.SELLER_FIRST_NAME__c, enrAfterUpdate.NAME_FIRST__c);
        SYSTEM.assertEquals(enrAfterUpdate.SELLER_LAST_NAME__c, enrAfterUpdate.NAME_LAST__c);
        SYSTEM.assertNotEquals(enrAfterUpdate.Seller_Name_Populated__c, null);
        SYSTEM.assertEquals(enrAfterUpdate.Seller_Date_Ordered__c, SYSTEM.TODAY());
    }
}