force-app/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Prospect</fullName>
                <default>true</default>
                <label>Prospect</label>
            </value>
            <value>
                <fullName>Active Client</fullName>
            </value>
            <value>
                <fullName>Dormant</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Inactive/Invalid</fullName>
            </value>
            <value>
                <fullName>Target_Client_Account</fullName>
                <label>Top Client Broker Account</label>
            </value>
            <value>
                <fullName>Target New Broker Account</fullName>
                <label>Top Prospect Broker Account</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/CCMID__c.field-meta.xml
<CustomField>
    <fullName>CCMID__c</fullName>
    <externalId>true</externalId>
    <label>CCMID</label>
    <length>25</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/CCMID__c.field-meta.xml
<CustomField>
    <fullName>CCMID__c</fullName>
    <externalId>true</externalId>
    <label>CCMID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrollment</label>
    <referenceTo>Enrollment__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Previous_CCMID__c.field-meta.xml
<CustomField>
    <fullName>Previous_CCMID__c</fullName>
    <description>If the CCMID changes based on recent Enrollments, this stores the previous value of the CCMID, before the change</description>
    <inlineHelpText>If the CCMID changes based on recent Enrollments, this stores the previous value of the CCMID, before the change</inlineHelpText>
    <label>Previous CCMID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>WR-{0000000}</displayFormat>
        <label>Warranty Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Agency_Office__c.field-meta.xml
<CustomField>
    <fullName>Agency_Office__c</fullName>
    <label>Agency / Office</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Agent_Address__c.field-meta.xml
<CustomField>
    <fullName>Agent_Address__c</fullName>
    <label>Agent Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Agent_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Agent_First_Name__c</fullName>
    <label>Agent First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Agent_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Agent_Last_Name__c</fullName>
    <label>Agent Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Agent_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Agent_Zip_Code__c</fullName>
    <label>Agent Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Base_year_zero_contract_value__c.field-meta.xml
<CustomField>
    <fullName>Base_year_zero_contract_value__c</fullName>
    <label>Base year zero contract value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/CCMID_of_Agency__c.field-meta.xml
<CustomField>
    <fullName>CCMID_of_Agency__c</fullName>
    <label>CCMID of Agency (on import)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/CCMID_of_Agent__c.field-meta.xml
<CustomField>
    <fullName>CCMID_of_Agent__c</fullName>
    <label>CCMID of Agent (on import)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Used by EnrollmentRoundup batch job</description>
    <inlineHelpText>Used by EnrollmentRoundup batch job</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Picked up by Queueable</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Warranty_Type__c.field-meta.xml
<CustomField>
    <fullName>Warranty_Type__c</fullName>
    <label>Warranty Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BCW</fullName>
            </value>
            <value>
                <fullName>BDW</fullName>
            </value>
            <value>
                <fullName>NHW</fullName>
            </value>
            <value>
                <fullName>ODW</fullName>
            </value>
            <value>
                <fullName>SHW</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AgentCCMIDConsolidation_Test.cls
@isTest
private  class AgentCCMIDConsolidation_Test 
{
   static TestMethod void testThis()
   {
       Test.startTest();
        AgentCCMIDConsolidation batchable = new AgentCCMIDConsolidation();
        Database.executeBatch(batchable);
        Test.stopTest();
        
        Contact con = [SELECT Id, CCMID__c FROM Contact LIMIT 1];
        SYSTEM.assertEquals(con.CCMID__c , '142434064');
   }

   static TestMethod void testThisWithQuery() 
   {
        String query = 'SELECT Id, CCMID__c, Previous_CCMID__c FROM Contact ';

        Test.startTest();
        AgentCCMIDConsolidation batchable = new AgentCCMIDConsolidation(query);
        Database.executeBatch(batchable);
        Test.stopTest();
        
        Contact con = [SELECT Id, CCMID__c FROM Contact LIMIT 1];
        SYSTEM.assertEquals(con.CCMID__c , '142434064');
   }

   public static String CRON_EXP = '0 0 0 15 3 ? 2022';

    static testmethod void testSchedulable()
    {
        Test.startTest();

        //Schedule the test job
        String jobId = System.schedule('ScheduleApexClassTest', CRON_EXP, 
                new AgentCCMIDConsolidation());
        
        // Get the info from the CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime
                         FROM CronTrigger WHERE Id =:jobId];
                         
        // Verify the expressions are the same
        System.assertEquals(CRON_EXP, ct.CronExpression);
        
        // Verify the job has not run
        System.assertEquals(0, ct.TimesTriggered);
        
        // Verify the next time the job will run
        System.assertEquals('2022-03-15 00:00:00', String.valueOf(ct.NextFireTime));

        Test.stopTest();
        
        // Verify the job has now run
        System.assertNotEquals(1, ct.TimesTriggered);
    }

   
   @TestSetup
   static void makeData()
   {
       Account testAgency = new Account();
       testAgency.Name = 'Test Agency';
       testAgency.CCMID__c = '141777791';
       testAgency.Account_Status__c = 'Prospect';
       testAgency.ShippingStreet = '3290 N RIDGE RD #150';
       testAgency.ShippingPostalCode = '21043';
       insert testAgency;

       Contact testAgent = new Contact();
       testAgent.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contacts for HMS').getRecordTypeId();
       testAgent.FirstName = 'ADRIENNE';
       testAgent.LastName = 'WAGNER';
       testAgent.Email = 'adrienne.wagner@roadrunner.com';
       testAgent.CCMID__c = '142437000';
       testAgent.AccountId = testAgency.Id;
       insert testAgent;

       Enrollment__c ENROlder = new Enrollment__c();
       ENROlder.Name = '11569457';
       ENROlder.Date_Ordered__c = SYSTEM.TODAY()-10;
       ENROlder.Warranty_Type__c = 'BCW';
       ENROlder.Base_year_zero_contract_value__c = 489.0;
       ENROlder.CCMID_of_Agency__c = testAgency.CCMID__c;
       ENROlder.Agent_Address__c = '3802 STATE RT. 31';
       ENROlder.Agent_Zip_Code__c = '15628';
       ENROlder.Agency_Office__c = 'BHHS THE PREFERRED REALTY - LAUREL HIGHLANDS BHHS';
       ENROlder.CCMID_of_Agent__c = '142437000';
       ENROlder.Agent_First_Name__c = 'ADRIENNE';
       ENROlder.Agent_Last_Name__c = 'WAGNER';
       ENROlder.Status__c = 'Success';
       ENROlder.Agent__c = testAgent.Id;
       insert ENROlder;

       Enrollment__c ENRNewer = new Enrollment__c();
       ENRNewer.Name = '11569458';
       ENRNewer.Date_Ordered__c = SYSTEM.TODAY()-5;
       ENRNewer.Warranty_Type__c = 'BCW';
       ENRNewer.Base_year_zero_contract_value__c = 489.0;
       ENRNewer.CCMID_of_Agency__c = testAgency.CCMID__c;
       ENRNewer.Agent_Address__c = '3802 STATE RT. 31';
       ENRNewer.Agent_Zip_Code__c = '15628';
       ENRNewer.Agency_Office__c = 'BHHS THE PREFERRED REALTY - LAUREL HIGHLANDS BHHS';
       ENRNewer.CCMID_of_Agent__c = '142434064';
       ENRNewer.Agent_First_Name__c = 'ADRIENNE';
       ENRNewer.Agent_Last_Name__c = 'WAGNER';
       ENRNewer.Status__c = 'Success';
       ENRNewer.Agent__c = testAgent.Id;
       insert ENRNewer;

   }
}