force-app/main/default/objects/Contact/fields/CCMID__c.field-meta.xml
<CustomField>
    <fullName>CCMID__c</fullName>
    <externalId>true</externalId>
    <label>CCMID</label>
    <length>30</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrollment</label>
    <referenceTo>Enrollment__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Previous_CCMID__c.field-meta.xml
<CustomField>
    <fullName>Previous_CCMID__c</fullName>
    <description>If the CCMID changes based on recent Enrollments, this stores the previous value of the CCMID, before the change</description>
    <inlineHelpText>If the CCMID changes based on recent Enrollments, this stores the previous value of the CCMID, before the change</inlineHelpText>
    <label>Previous CCMID</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>WR-{0000000}</displayFormat>
        <label>Warranty Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/CCMID_of_Agent__c.field-meta.xml
<CustomField>
    <fullName>CCMID_of_Agent__c</fullName>
    <label>CCMID of Agent (on import)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/CCMID_of_Agent_formula__c.field-meta.xml
<CustomField>
    <fullName>CCMID_of_Agent_formula__c</fullName>
    <formula>Agent__r.CCMID__c</formula>
    <inlineHelpText>Pulled in from Agent</inlineHelpText>
    <label>CCMID of Agent (f)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Used by EnrollmentRoundup batch job</description>
    <inlineHelpText>Used by EnrollmentRoundup batch job</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Picked up by Queueable</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AgentCCMIDConsolidation.cls
global with sharing class AgentCCMIDConsolidation implements Database.Batchable<SObject>, Schedulable 
{
    /* Rackspace, David Berman, 11 September 2020

     * Agents with multiple CCMIDs
     * To help correct this, need to identify an agent with multiple CCMIDs, 
     * then reference all CCMIDs that exist for that 1 agent (contact) and,
     * then select the one that has been enrolled to most recently. 
     * The CCMID that was enrolled to most recently would then become the "Master" CCMID 
     * for that agent (contact) and all enrollments that are associated with that agent (contact) 
     * would then also be updated to have that "master" CCMID.
     */

    String query;
    global static String defaultAgent = Label.Contact_Enrollment_CCMID_Not_Found;
    ID IDContactTACoordinatorsRecType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('TA Coordinators').getRecordTypeId();
    ID IDContactContactsHMSRecType = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Contacts for HMS').getRecordTypeId();
        
    Set<Id> setAgentRecordTypes = new Set<Id>{IDContactTACoordinatorsRecType, IDContactContactsHMSRecType};

    global AgentCCMIDConsolidation() 
    {
        query = 'SELECT Id, CCMID__c, Previous_CCMID__c '+
                'FROM Contact ' + 
                'WHERE RecordTypeId IN :setAgentRecordTypes ';
        query += Test.isRunningTest() ? ' LIMIT 10' : '';
    }

    global AgentCCMIDConsolidation(String customQuery)
    {
        query = customQuery;
    }


    global Database.QueryLocator start(Database.BatchableContext BC) 
    {
        return Database.getQueryLocator(query);
    }
    
    global void execute(Database.BatchableContext BC, List<Contact> scope) 
    {
        Integer iListSize = scope.size();
        Integer i = 0;

        Set<ID> setContactIDs = new Set<Id>();
        while(i < iListSize)
        {
            setContactIDs.add(scope[i].Id);
            i++;
        }

        List<Enrollment__c> listEnrollmentsForAgents;
        try 
        {
            listEnrollmentsForAgents = new List<Enrollment__c>(
                [SELECT Id, CCMID_of_Agent__c, CCMID_of_Agent_formula__c, Agent__c, Date_Ordered__c 
                FROM Enrollment__c
                WHERE Status__c = 'Success'
                    AND Agent__c IN :setContactIDs
                ORDER BY Agent__c, Date_Ordered__c DESC, CCMID_of_Agent__c DESC]
            );
        }catch (Exception exEnrollments) {}


        Integer iEnrollmentsListSize = listEnrollmentsForAgents.size();
        Integer j = 0;
        Map<Id, Contact> mapContactUpdates = new Map<Id, Contact>();
        while(j < iEnrollmentsListSize)
        {
            Enrollment__c ENR = listEnrollmentsForAgents[j];
            j++;

            if(!mapContactUpdates.containsKey(ENR.Agent__c) && ENR.CCMID_of_Agent__c != ENR.CCMID_of_Agent_formula__c)
            {
                Contact conUpdate = new Contact();
                conUpdate.Id = ENR.Agent__c;
                conUpdate.Previous_CCMID__c = ENR.CCMID_of_Agent_formula__c;
                conUpdate.CCMID__c = ENR.CCMID_of_Agent__c;

                mapContactUpdates.put(ENR.Agent__c, conUpdate);
            }
        }

        if(mapContactUpdates.size() > 0)
        {
            AgentCCMIDConsolidationQueueable updateContactsAsynchronously = new AgentCCMIDConsolidationQueueable(mapContactUpdates.values());
        	SYSTEM.enqueueJob( updateContactsAsynchronously );  
        }

    }

    global void execute(SchedulableContext sc) 
    {  
        AgentCCMIDConsolidation batch = new AgentCCMIDConsolidation();
        Database.executeBatch(batch, 200);
    }

    global void finish(Database.BatchableContext BC) 
    {

    }

}