force-app/main/default/objects/Contact/fields/Enrollment__c.field-meta.xml
<CustomField>
    <fullName>Enrollment__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Enrollment</label>
    <referenceTo>Enrollment__c</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/Enrollment__c.object-meta.xml
<CustomObject>
    <label>Enrollment</label>
    <nameField>
        <displayFormat>WR-{0000000}</displayFormat>
        <label>Warranty Record</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Enrollments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Enrollment__c/fields/Agency__c.field-meta.xml
<CustomField>
    <fullName>Agency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agency</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Agency_Office__c.field-meta.xml
<CustomField>
    <fullName>Agency_Office__c</fullName>
    <label>Agency / Office</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Agent</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Enrollments</relationshipLabel>
    <relationshipName>Enrollments1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Agent_Address__c.field-meta.xml
<CustomField>
    <fullName>Agent_Address__c</fullName>
    <label>Agent Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Agent_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Agent_First_Name__c</fullName>
    <label>Agent First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Agent_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Agent_Last_Name__c</fullName>
    <label>Agent Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Agent_Zip_Code__c.field-meta.xml
<CustomField>
    <fullName>Agent_Zip_Code__c</fullName>
    <label>Agent Zip Code</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/CCMID_of_Agency__c.field-meta.xml
<CustomField>
    <fullName>CCMID_of_Agency__c</fullName>
    <label>CCMID of Agency (on import)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/CCMID_of_Agent__c.field-meta.xml
<CustomField>
    <fullName>CCMID_of_Agent__c</fullName>
    <label>CCMID of Agent (on import)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Enrollment__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Used by EnrollmentRoundup batch job</description>
    <inlineHelpText>Used by EnrollmentRoundup batch job</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Retry</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
            <value>
                <fullName>Picked up by Queueable</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EnrollmentRoundup_Test.cls
@isTest
private class EnrollmentRoundup_Test 
{
    @TestSetup
	static void setupTestData()
    {
        Account acc = new Account(Name = Label.Account_Enrollment_CCMID_Not_Found_TEST );
        insert acc;
        
        Contact con = new Contact(LastName = Label.Contact_Enrollment_CCMID_Not_Found_for_TEST , AccountId = acc.Id);
        insert con;    
    }
 
    
    static TestMethod void testBatchDefaultAgentAndAgency()
    {
                
        Enrollment__c Enr = new Enrollment__c();
        Enr.Status__c = 'New';
        Enr.Agency_Office__c = 'Test Office';
        Enr.Agent_Address__c = 'Test Street 1';
        Enr.CCMID_of_Agency__c = 'Agency1000';
        Enr.Agent_Zip_Code__c = '99999';
        Enr.Agent_First_Name__c = 'JOHN';
        Enr.Agent_Last_Name__c = 'DOE';
        Enr.CCMID_of_Agent__c = 'Agent8000';
        Enr.Agency__c = [SELECT ID FROM Account WHERE Name = :Label.Account_Enrollment_CCMID_Not_Found_TEST LIMIT 1].Id;
        Enr.Agent__c = [SELECT ID FROM Contact WHERE LastName = :Label.Contact_Enrollment_CCMID_Not_Found_for_TEST LIMIT 1].Id;
        insert Enr;
        
        Test.startTest();
        EnrollmentRoundup batch = new EnrollmentRoundup();
        Database.executeBatch(batch, 1);
        Test.stopTest();
        
    }
 
    
    public static String CRON_EXP = '0 0 0 15 3 ? 2022';

    static testmethod void testSchedulable()
    {
        Test.startTest();

        //Schedule the test job
        String jobId = System.schedule('ScheduleApexClassTest', CRON_EXP, 
                new EnrollmentRoundup());
        
        // Get the info from the CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime
                         FROM CronTrigger WHERE Id =:jobId];
                         
        // Verify the expressions are the same
        System.assertEquals(CRON_EXP, ct.CronExpression);
        
        // Verify the job has not run
        System.assertEquals(0, ct.TimesTriggered);
        
        // Verify the next time the job will run
        System.assertEquals('2022-03-15 00:00:00', String.valueOf(ct.NextFireTime));

        Test.stopTest();
        
        // Verify the job has now run
        System.assertNotEquals(1, ct.TimesTriggered);
    }
}